<?php
/*provincias=[
['1' => Alava '2' => Albacete '3' => Alicante '4' => Almería '5' => Ávila 
'6' => Badajoz '7' => Illes Balears '8' => Barcelona '9' => Burgos 
'10' => Cáceres '11' => Cádiz '12' => Castellón '13' => Ciudad Real 
'14' => Cordoba '15' => A Coruña '16' => Cuenca '17' => Girona '18' => Granada 
'19' => Guadalajara '20' => Guipúzcoa '21' => Huelva '22' => Huesca '23' => Jaén 
'24' => León '25' => Lleida '26' => La Rioja '27' => Lugo '28' => Madrid '29' => Málaga 
'30' => 'Murcia', '31' => 'Navarra ','32' => Ourense '33' => Asturias '34' => Palencia 
'35' => 'Las Palmas' ,'36' => 'Pontevedra', '37' => 'Salamanca, '38' => 'Santa Cruz de Tenerife ',
'39' => 'Cantabria', '40' => 'Segovia','41' => 'Sevilla', '42' => Soria '43' => 'Tarragona' ,
'44' => 'Teruel' ,'45' => 'Toledo' ,'46' => 'Valencia' ,'47' => 'Valladolid', '48' => 'Vizcaya' ,
'49' => 'Zamora', '50' => 'Zaragoza', '51' => 'Ceuta' ,'52' => 'Melilla'];*/

$ofertas=[
 ['id' => '1 ','descripcion' => 'Tecnico de Farmacia', 'contacto' =>'Enrique Velardo', 'telefono' =>'959235685',  'email' => 'kikeV@gmail.com', 'direccion' =>'c/Mal Augurio 28' ,'poblacion' =>' La Puebla de Guzman', 'cp' => '21004', 'id_provincia' => '21', 'provincia' => 'Huelva', 'estado' =>' P', 'fechaInicial' => '13/11/2018', 'fechaFin' => '18/11/2030' ,'psicologo' => 'Maria Luna Lunera', 'candidato' => 'Daniel Prieto', 'observaciones' => ''],
 ['id' => '2 ','descripcion' => 'Tecnico de Farmacia', 'contacto' =>'Enrique Velardo', 'telefono' =>'959235685',  'email' => 'kikeV@gmail.com', 'direccion' =>'c/Mal Augurio 28' ,'poblacion' =>' La Puebla de Guzman', 'cp' => '21004', 'id_provincia' => '21', 'provincia' => 'Huelva', 'estado' =>' P', 'fechaInicial' => '13/11/2018', 'fechaFin' => '18/11/2030' ,'psicologo' => 'Maria Luna Lunera', 'candidato' => 'Daniel Prieto', 'observaciones' => ''],
 ['id' => '3 ','descripcion' => 'Tecnico de Farmacia', 'contacto' =>'Enrique Velardo', 'telefono' =>'959235685',  'email' => 'kikeV@gmail.com', 'direccion' =>'c/Mal Augurio 28' ,'poblacion' =>' La Puebla de Guzman', 'cp' => '21004', 'id_provincia' => '21', 'provincia' => 'Huelva', 'estado' =>' P', 'fechaInicial' => '13/11/2018', 'fechaFin' => '18/11/2030' ,'psicologo' => 'Maria Luna Lunera', 'candidato' => 'Daniel Prieto', 'observaciones' => ''],
 ['id' => '4 ','descripcion' => 'Tecnico de Farmacia', 'contacto' =>'Enrique Velardo', 'telefono' =>'959235685',  'email' => 'kikeV@gmail.com', 'direccion' =>'c/Mal Augurio 28' ,'poblacion' =>' La Puebla de Guzman', 'cp' => '21004', 'id_provincia' => '21', 'provincia' => 'Huelva', 'estado' =>' P', 'fechaInicial' => '13/11/2018', 'fechaFin' => '18/11/2030' ,'psicologo' => 'Maria Luna Lunera', 'candidato' => 'Daniel Prieto', 'observaciones' => ''],
 ['id' => '5 ','descripcion' => 'Tecnico de Farmacia', 'contacto' =>'Enrique Velardo', 'telefono' =>'959235685',  'email' => 'kikeV@gmail.com', 'direccion' =>'c/Mal Augurio 28' ,'poblacion' =>' La Puebla de Guzman', 'cp' => '21004', 'id_provincia' => '21', 'provincia' => 'Huelva', 'estado' =>' P', 'fechaInicial' => '13/11/2018', 'fechaFin' => '18/11/2030' ,'psicologo' => 'Maria Luna Lunera', 'candidato' => 'Daniel Prieto', 'observaciones' => ''],
 ['id' => '6 ','descripcion' => 'Tecnico de Farmacia', 'contacto' =>'Enrique Velardo', 'telefono' =>'959235685',  'email' => 'kikeV@gmail.com', 'direccion' =>'c/Mal Augurio 28' ,'poblacion' =>' La Puebla de Guzman', 'cp' => '21004', 'id_provincia' => '21', 'provincia' => 'Huelva', 'estado' =>' P', 'fechaInicial' => '13/11/2018', 'fechaFin' => '18/11/2030' ,'psicologo' => 'Maria Luna Lunera', 'candidato' => 'Daniel Prieto', 'observaciones' => ''],
 ['id' => '7 ','descripcion' => 'Tecnico de Farmacia', 'contacto' =>'Enrique Velardo', 'telefono' =>'959235685',  'email' => 'kikeV@gmail.com', 'direccion' =>'c/Mal Augurio 28' ,'poblacion' =>' La Puebla de Guzman', 'cp' => '21004', 'id_provincia' => '21', 'provincia' => 'Huelva', 'estado' =>' P', 'fechaInicial' => '13/11/2018', 'fechaFin' => '18/11/2030' ,'psicologo' => 'Maria Luna Lunera', 'candidato' => 'Daniel Prieto', 'observaciones' => ''],
 ['id' => '8 ','descripcion' => 'Tecnico de Farmacia', 'contacto' =>'Enrique Velardo', 'telefono' =>'959235685',  'email' => 'kikeV@gmail.com', 'direccion' =>'c/Mal Augurio 28' ,'poblacion' =>' La Puebla de Guzman', 'cp' => '21004', 'id_provincia' => '21', 'provincia' => 'Huelva', 'estado' =>' P', 'fechaInicial' => '13/11/2018', 'fechaFin' => '18/11/2030' ,'psicologo' => 'Maria Luna Lunera', 'candidato' => 'Daniel Prieto', 'observaciones' => ''],
 ['id' => '9 ','descripcion' => 'Tecnico de Farmacia', 'contacto' =>'Enrique Velardo', 'telefono' =>'959235685',  'email' => 'kikeV@gmail.com', 'direccion' =>'c/Mal Augurio 28' ,'poblacion' =>' La Puebla de Guzman', 'cp' => '21004', 'id_provincia' => '21', 'provincia' => 'Huelva', 'estado' =>' P', 'fechaInicial' => '13/11/2018', 'fechaFin' => '18/11/2030' ,'psicologo' => 'Maria Luna Lunera', 'candidato' => 'Daniel Prieto', 'observaciones' => ''],
 ['id' => '10 ','descripcion' => 'Tecnico de Farmacia', 'contacto' =>'Enrique Velardo', 'telefono' =>'959235685',  'email' => 'kikeV@gmail.com', 'direccion' =>'c/Mal Augurio 28' ,'poblacion' =>' La Puebla de Guzman', 'cp' => '21004', 'id_provincia' => '21', 'provincia' => 'Huelva', 'estado' =>' P', 'fechaInicial' => '13/11/2018', 'fechaFin' => '18/11/2030' ,'psicologo' => 'Maria Luna Lunera', 'candidato' => 'Daniel Prieto', 'observaciones' => ''],
 ['id' => '11','descripcion' => 'Tecnico de Farmacia', 'contacto' =>'Enrique Velardo', 'telefono' =>'959235685',  'email' => 'kikeV@gmail.com', 'direccion' =>'c/Mal Augurio 28' ,'poblacion' =>' La Puebla de Guzman', 'cp' => '21004', 'id_provincia' => '21', 'provincia' => 'Huelva', 'estado' =>' P', 'fechaInicial' => '13/11/2018', 'fechaFin' => '18/11/2030' ,'psicologo' => 'Maria Luna Lunera', 'candidato' => 'Daniel Prieto', 'observaciones' => ''],
 ['id' => '12','descripcion' => 'Tecnico de Farmacia', 'contacto' =>'Enrique Velardo', 'telefono' =>'959235685',  'email' => 'kikeV@gmail.com', 'direccion' =>'c/Mal Augurio 28' ,'poblacion' =>' La Puebla de Guzman', 'cp' => '21004', 'id_provincia' => '21', 'provincia' => 'Huelva', 'estado' =>' P', 'fechaInicial' => '13/11/2018', 'fechaFin' => '18/11/2030' ,'psicologo' => 'Maria Luna Lunera', 'candidato' => 'Daniel Prieto', 'observaciones' => ''],
 ['id' => '13','descripcion' => 'Tecnico de Farmacia', 'contacto' =>'Enrique Velardo', 'telefono' =>'959235685',  'email' => 'kikeV@gmail.com', 'direccion' =>'c/Mal Augurio 28' ,'poblacion' =>' La Puebla de Guzman', 'cp' => '21004', 'id_provincia' => '21', 'provincia' => 'Huelva', 'estado' =>' P', 'fechaInicial' => '13/11/2018', 'fechaFin' => '18/11/2030' ,'psicologo' => 'Maria Luna Lunera', 'candidato' => 'Daniel Prieto', 'observaciones' => ''],
 ['id' => '14','descripcion' => 'Tecnico de Farmacia', 'contacto' =>'Enrique Velardo', 'telefono' =>'959235685',  'email' => 'kikeV@gmail.com', 'direccion' =>'c/Mal Augurio 28' ,'poblacion' =>' La Puebla de Guzman', 'cp' => '21004', 'id_provincia' => '21', 'provincia' => 'Huelva', 'estado' =>' P', 'fechaInicial' => '13/11/2018', 'fechaFin' => '18/11/2030' ,'psicologo' => 'Maria Luna Lunera', 'candidato' => 'Daniel Prieto', 'observaciones' => ''],
 ['id' => '15','descripcion' => 'Tecnico de Farmacia', 'contacto' =>'Enrique Velardo', 'telefono' =>'959235685',  'email' => 'kikeV@gmail.com', 'direccion' =>'c/Mal Augurio 28' ,'poblacion' =>' La Puebla de Guzman', 'cp' => '21004', 'id_provincia' => '21', 'provincia' => 'Huelva', 'estado' =>' P', 'fechaInicial' => '13/11/2018', 'fechaFin' => '18/11/2030' ,'psicologo' => 'Maria Luna Lunera', 'candidato' => 'Daniel Prieto', 'observaciones' => ''],
 ['id' => '16','descripcion' => 'Tecnico de Farmacia', 'contacto' =>'Enrique Velardo', 'telefono' =>'959235685',  'email' => 'kikeV@gmail.com', 'direccion' =>'c/Mal Augurio 28' ,'poblacion' =>' La Puebla de Guzman', 'cp' => '21004', 'id_provincia' => '21', 'provincia' => 'Huelva', 'estado' =>' P', 'fechaInicial' => '13/11/2018', 'fechaFin' => '18/11/2030' ,'psicologo' => 'Maria Luna Lunera', 'candidato' => 'Daniel Prieto', 'observaciones' => ''],
 ['id' => '17','descripcion' => 'Tecnico de Farmacia', 'contacto' =>'Enrique Velardo', 'telefono' =>'959235685',  'email' => 'kikeV@gmail.com', 'direccion' =>'c/Mal Augurio 28' ,'poblacion' =>' La Puebla de Guzman', 'cp' => '21004', 'id_provincia' => '21', 'provincia' => 'Huelva', 'estado' =>' P', 'fechaInicial' => '13/11/2018', 'fechaFin' => '18/11/2030' ,'psicologo' => 'Maria Luna Lunera', 'candidato' => 'Daniel Prieto', 'observaciones' => ''],
 ['id' => '18','descripcion' => 'Tecnico de Farmacia', 'contacto' =>'Enrique Velardo', 'telefono' =>'959235685',  'email' => 'kikeV@gmail.com', 'direccion' =>'c/Mal Augurio 28' ,'poblacion' =>' La Puebla de Guzman', 'cp' => '21004', 'id_provincia' => '21', 'provincia' => 'Huelva', 'estado' =>' P', 'fechaInicial' => '13/11/2018', 'fechaFin' => '18/11/2030' ,'psicologo' => 'Maria Luna Lunera', 'candidato' => 'Daniel Prieto', 'observaciones' => ''],
 ['id' => '20','descripcion' => 'Tecnico de Farmacia', 'contacto' =>'Enrique Velardo', 'telefono' =>'959235685',  'email' => 'kikeV@gmail.com', 'direccion' =>'c/Mal Augurio 28' ,'poblacion' =>' La Puebla de Guzman', 'cp' => '21004', 'id_provincia' => '21', 'provincia' => 'Huelva', 'estado' =>' P', 'fechaInicial' => '13/11/2018', 'fechaFin' => '18/11/2030' ,'psicologo' => 'Maria Luna Lunera', 'candidato' => 'Daniel Prieto', 'observaciones' => ''],
 ['id' => '21','descripcion' => 'Tecnico de Farmacia', 'contacto' =>'Enrique Velardo', 'telefono' =>'959235685',  'email' => 'kikeV@gmail.com', 'direccion' =>'c/Mal Augurio 28' ,'poblacion' =>' La Puebla de Guzman', 'cp' => '21004', 'id_provincia' => '21', 'provincia' => 'Huelva', 'estado' =>' P', 'fechaInicial' => '13/11/2018', 'fechaFin' => '18/11/2030' ,'psicologo' => 'Maria Luna Lunera', 'candidato' => 'Daniel Prieto', 'observaciones' => ''],
 ['id' => '22','descripcion' => 'Tecnico de Farmacia', 'contacto' =>'Enrique Velardo', 'telefono' =>'959235685',  'email' => 'kikeV@gmail.com', 'direccion' =>'c/Mal Augurio 28' ,'poblacion' =>' La Puebla de Guzman', 'cp' => '21004', 'id_provincia' => '21', 'provincia' => 'Huelva', 'estado' =>' P', 'fechaInicial' => '13/11/2018', 'fechaFin' => '18/11/2030' ,'psicologo' => 'Maria Luna Lunera', 'candidato' => 'Daniel Prieto', 'observaciones' => ''],
 ['id' => '23 ','descripcion' => 'Tecnico de Farmacia', 'contacto' =>'Enrique Velardo', 'telefono' =>'959235685',  'email' => 'kikeV@gmail.com', 'direccion' =>'c/Mal Augurio 28' ,'poblacion' =>' La Puebla de Guzman', 'cp' => '21004', 'id_provincia' => '21', 'provincia' => 'Huelva', 'estado' =>' P', 'fechaInicial' => '13/11/2018', 'fechaFin' => '18/11/2030' ,'psicologo' => 'Maria Luna Lunera', 'candidato' => 'Daniel Prieto', 'observaciones' => ''],
 ['id' => '24 ','descripcion' => 'Tecnico de Farmacia', 'contacto' =>'Enrique Velardo', 'telefono' =>'959235685',  'email' => 'kikeV@gmail.com', 'direccion' =>'c/Mal Augurio 28' ,'poblacion' =>' La Puebla de Guzman', 'cp' => '21004', 'id_provincia' => '21', 'provincia' => 'Huelva', 'estado' =>' P', 'fechaInicial' => '13/11/2018', 'fechaFin' => '18/11/2030' ,'psicologo' => 'Maria Luna Lunera', 'candidato' => 'Daniel Prieto', 'observaciones' => ''],
 ['id' => '25 ','descripcion' => 'Tecnico de Farmacia', 'contacto' =>'Enrique Velardo', 'telefono' =>'959235685',  'email' => 'kikeV@gmail.com', 'direccion' =>'c/Mal Augurio 28' ,'poblacion' =>' La Puebla de Guzman', 'cp' => '21004', 'id_provincia' => '21', 'provincia' => 'Huelva', 'estado' =>' P', 'fechaInicial' => '13/11/2018', 'fechaFin' => '18/11/2030' ,'psicologo' => 'Maria Luna Lunera', 'candidato' => 'Daniel Prieto', 'observaciones' => ''],
 ['id' => '26 ','descripcion' => 'Tecnico de Farmacia', 'contacto' =>'Enrique Velardo', 'telefono' =>'959235685',  'email' => 'kikeV@gmail.com', 'direccion' =>'c/Mal Augurio 28' ,'poblacion' =>' La Puebla de Guzman', 'cp' => '21004', 'id_provincia' => '21', 'provincia' => 'Huelva', 'estado' =>' P', 'fechaInicial' => '13/11/2018', 'fechaFin' => '18/11/2030' ,'psicologo' => 'Maria Luna Lunera', 'candidato' => 'Daniel Prieto', 'observaciones' => ''],
 ['id' => '27 ','descripcion' => 'Tecnico de Farmacia', 'contacto' =>'Enrique Velardo', 'telefono' =>'959235685',  'email' => 'kikeV@gmail.com', 'direccion' =>'c/Mal Augurio 28' ,'poblacion' =>' La Puebla de Guzman', 'cp' => '21004', 'id_provincia' => '21', 'provincia' => 'Huelva', 'estado' =>' P', 'fechaInicial' => '13/11/2018', 'fechaFin' => '18/11/2030' ,'psicologo' => 'Maria Luna Lunera', 'candidato' => 'Daniel Prieto', 'observaciones' => ''],
 ['id' => '28 ','descripcion' => 'Tecnico de Farmacia', 'contacto' =>'Enrique Velardo', 'telefono' =>'959235685',  'email' => 'kikeV@gmail.com', 'direccion' =>'c/Mal Augurio 28' ,'poblacion' =>' La Puebla de Guzman', 'cp' => '21004', 'id_provincia' => '21', 'provincia' => 'Huelva', 'estado' =>' P', 'fechaInicial' => '13/11/2018', 'fechaFin' => '18/11/2030' ,'psicologo' => 'Maria Luna Lunera', 'candidato' => 'Daniel Prieto', 'observaciones' => ''],
 ['id' => '29 ','descripcion' => 'Tecnico de Farmacia', 'contacto' =>'Enrique Velardo', 'telefono' =>'959235685',  'email' => 'kikeV@gmail.com', 'direccion' =>'c/Mal Augurio 28' ,'poblacion' =>' La Puebla de Guzman', 'cp' => '21004', 'id_provincia' => '21', 'provincia' => 'Huelva', 'estado' =>' P', 'fechaInicial' => '13/11/2018', 'fechaFin' => '18/11/2030' ,'psicologo' => 'Maria Luna Lunera', 'candidato' => 'Daniel Prieto', 'observaciones' => ''],
 ['id' => '30 ','descripcion' => 'Tecnico de Farmacia', 'contacto' =>'Enrique Velardo', 'telefono' =>'959235685',  'email' => 'kikeV@gmail.com', 'direccion' =>'c/Mal Augurio 28' ,'poblacion' =>' La Puebla de Guzman', 'cp' => '21004', 'id_provincia' => '21', 'provincia' => 'Huelva', 'estado' =>' P', 'fechaInicial' => '13/11/2018', 'fechaFin' => '18/11/2030' ,'psicologo' => 'Maria Luna Lunera', 'candidato' => 'Daniel Prieto', 'observaciones' => ''],
 ['id' => '31 ','descripcion' => 'Tecnico de Farmacia', 'contacto' =>'Enrique Velardo', 'telefono' =>'959235685',  'email' => 'kikeV@gmail.com', 'direccion' =>'c/Mal Augurio 28' ,'poblacion' =>' La Puebla de Guzman', 'cp' => '21004', 'id_provincia' => '21', 'provincia' => 'Huelva', 'estado' =>' P', 'fechaInicial' => '13/11/2018', 'fechaFin' => '18/11/2030' ,'psicologo' => 'Maria Luna Lunera', 'candidato' => 'Daniel Prieto', 'observaciones' => ''],
 ['id' => '32','descripcion' => 'Tecnico de Farmacia', 'contacto' =>'Enrique Velardo', 'telefono' =>'959235685',  'email' => 'kikeV@gmail.com', 'direccion' =>'c/Mal Augurio 28' ,'poblacion' =>' La Puebla de Guzman', 'cp' => '21004', 'id_provincia' => '21', 'provincia' => 'Huelva', 'estado' =>' P', 'fechaInicial' => '13/11/2018', 'fechaFin' => '18/11/2030' ,'psicologo' => 'Maria Luna Lunera', 'candidato' => 'Daniel Prieto', 'observaciones' => ''],
 ['id' => '33 ','descripcion' => 'Tecnico de Farmacia', 'contacto' =>'Enrique Velardo', 'telefono' =>'959235685',  'email' => 'kikeV@gmail.com', 'direccion' =>'c/Mal Augurio 28' ,'poblacion' =>' La Puebla de Guzman', 'cp' => '21004', 'id_provincia' => '21', 'provincia' => 'Huelva', 'estado' =>' P', 'fechaInicial' => '13/11/2018', 'fechaFin' => '18/11/2030' ,'psicologo' => 'Maria Luna Lunera', 'candidato' => 'Daniel Prieto', 'observaciones' => ''],
 ['id' => '34 ','descripcion' => 'Tecnico de Farmacia', 'contacto' =>'Enrique Velardo', 'telefono' =>'959235685',  'email' => 'kikeV@gmail.com', 'direccion' =>'c/Mal Augurio 28' ,'poblacion' =>' La Puebla de Guzman', 'cp' => '21004', 'id_provincia' => '21', 'provincia' => 'Huelva', 'estado' =>' P', 'fechaInicial' => '13/11/2018', 'fechaFin' => '18/11/2030' ,'psicologo' => 'Maria Luna Lunera', 'candidato' => 'Daniel Prieto', 'observaciones' => ''],
 ['id' => '35 ','descripcion' => 'Tecnico de Farmacia', 'contacto' =>'Enrique Velardo', 'telefono' =>'959235685',  'email' => 'kikeV@gmail.com', 'direccion' =>'c/Mal Augurio 28' ,'poblacion' =>' La Puebla de Guzman', 'cp' => '21004', 'id_provincia' => '21', 'provincia' => 'Huelva', 'estado' =>' P', 'fechaInicial' => '13/11/2018', 'fechaFin' => '18/11/2030' ,'psicologo' => 'Maria Luna Lunera', 'candidato' => 'Daniel Prieto', 'observaciones' => ''],
 ['id' => '36 ','descripcion' => 'Tecnico de Farmacia', 'contacto' =>'Enrique Velardo', 'telefono' =>'959235685',  'email' => 'kikeV@gmail.com', 'direccion' =>'c/Mal Augurio 28' ,'poblacion' =>' La Puebla de Guzman', 'cp' => '21004', 'id_provincia' => '21', 'provincia' => 'Huelva', 'estado' =>' P', 'fechaInicial' => '13/11/2018', 'fechaFin' => '18/11/2030' ,'psicologo' => 'Maria Luna Lunera', 'candidato' => 'Daniel Prieto', 'observaciones' => ''],
 ['id' => '37 ','descripcion' => 'Tecnico de Farmacia', 'contacto' =>'Enrique Velardo', 'telefono' =>'959235685',  'email' => 'kikeV@gmail.com', 'direccion' =>'c/Mal Augurio 28' ,'poblacion' =>' La Puebla de Guzman', 'cp' => '21004', 'id_provincia' => '21', 'provincia' => 'Huelva', 'estado' =>' P', 'fechaInicial' => '13/11/2018', 'fechaFin' => '18/11/2030' ,'psicologo' => 'Maria Luna Lunera', 'candidato' => 'Daniel Prieto', 'observaciones' => ''],
 ['id' => '38 ','descripcion' => 'Tecnico de Farmacia', 'contacto' =>'Enrique Velardo', 'telefono' =>'959235685',  'email' => 'kikeV@gmail.com', 'direccion' =>'c/Mal Augurio 28' ,'poblacion' =>' La Puebla de Guzman', 'cp' => '21004', 'id_provincia' => '21', 'provincia' => 'Huelva', 'estado' =>' P', 'fechaInicial' => '13/11/2018', 'fechaFin' => '18/11/2030' ,'psicologo' => 'Maria Luna Lunera', 'candidato' => 'Daniel Prieto', 'observaciones' => ''],
 ['id' => '39','descripcion' => 'Tecnico de Farmacia', 'contacto' =>'Enrique Velardo', 'telefono' =>'959235685',  'email' => 'kikeV@gmail.com', 'direccion' =>'c/Mal Augurio 28' ,'poblacion' =>' La Puebla de Guzman', 'cp' => '21004', 'id_provincia' => '21', 'provincia' => 'Huelva', 'estado' =>' P', 'fechaInicial' => '13/11/2018', 'fechaFin' => '18/11/2030' ,'psicologo' => 'Maria Luna Lunera', 'candidato' => 'Daniel Prieto', 'observaciones' => ''],
 ['id' => '40','descripcion' => 'Tecnico de Farmacia', 'contacto' =>'Enrique Velardo', 'telefono' =>'959235685',  'email' => 'kikeV@gmail.com', 'direccion' =>'c/Mal Augurio 28' ,'poblacion' =>' La Puebla de Guzman', 'cp' => '21004', 'id_provincia' => '21', 'provincia' => 'Huelva', 'estado' =>' P', 'fechaInicial' => '13/11/2018', 'fechaFin' => '18/11/2030' ,'psicologo' => 'Maria Luna Lunera', 'candidato' => 'Daniel Prieto', 'observaciones' => ''],
 ['id' => '41 ','descripcion' => 'Tecnico de Farmacia', 'contacto' =>'Enrique Velardo', 'telefono' =>'959235685',  'email' => 'kikeV@gmail.com', 'direccion' =>'c/Mal Augurio 28' ,'poblacion' =>' La Puebla de Guzman', 'cp' => '21004', 'id_provincia' => '21', 'provincia' => 'Huelva', 'estado' =>' P', 'fechaInicial' => '13/11/2018', 'fechaFin' => '18/11/2030' ,'psicologo' => 'Maria Luna Lunera', 'candidato' => 'Daniel Prieto', 'observaciones' => ''],
 ['id' => '42 ','descripcion' => 'Tecnico de Farmacia', 'contacto' =>'Enrique Velardo', 'telefono' =>'959235685',  'email' => 'kikeV@gmail.com', 'direccion' =>'c/Mal Augurio 28' ,'poblacion' =>' La Puebla de Guzman', 'cp' => '21004', 'id_provincia' => '21', 'provincia' => 'Huelva', 'estado' =>' P', 'fechaInicial' => '13/11/2018', 'fechaFin' => '18/11/2030' ,'psicologo' => 'Maria Luna Lunera', 'candidato' => 'Daniel Prieto', 'observaciones' => ''],
 ['id' => '43 ','descripcion' => 'Tecnico de Farmacia', 'contacto' =>'Enrique Velardo', 'telefono' =>'959235685',  'email' => 'kikeV@gmail.com', 'direccion' =>'c/Mal Augurio 28' ,'poblacion' =>' La Puebla de Guzman', 'cp' => '21004', 'id_provincia' => '21', 'provincia' => 'Huelva', 'estado' =>' P', 'fechaInicial' => '13/11/2018', 'fechaFin' => '18/11/2030' ,'psicologo' => 'Maria Luna Lunera', 'candidato' => 'Daniel Prieto', 'observaciones' => ''],
 ['id' => '44','descripcion' => 'Tecnico de Farmacia', 'contacto' =>'Enrique Velardo', 'telefono' =>'959235685',  'email' => 'kikeV@gmail.com', 'direccion' =>'c/Mal Augurio 28' ,'poblacion' =>' La Puebla de Guzman', 'cp' => '21004', 'id_provincia' => '21', 'provincia' => 'Huelva', 'estado' =>' P', 'fechaInicial' => '13/11/2018', 'fechaFin' => '18/11/2030' ,'psicologo' => 'Maria Luna Lunera', 'candidato' => 'Daniel Prieto', 'observaciones' => ''],
 ['id' => '45 ','descripcion' => 'Tecnico de Farmacia', 'contacto' =>'Enrique Velardo', 'telefono' =>'959235685',  'email' => 'kikeV@gmail.com', 'direccion' =>'c/Mal Augurio 28' ,'poblacion' =>' La Puebla de Guzman', 'cp' => '21004', 'id_provincia' => '21', 'provincia' => 'Huelva', 'estado' =>' P', 'fechaInicial' => '13/11/2018', 'fechaFin' => '18/11/2030' ,'psicologo' => 'Maria Luna Lunera', 'candidato' => 'Daniel Prieto', 'observaciones' => ''],
 ['id' => '46','descripcion' => 'Tecnico de Farmacia', 'contacto' =>'Enrique Velardo', 'telefono' =>'959235685',  'email' => 'kikeV@gmail.com', 'direccion' =>'c/Mal Augurio 28' ,'poblacion' =>' La Puebla de Guzman', 'cp' => '21004', 'id_provincia' => '21', 'provincia' => 'Huelva', 'estado' =>' P', 'fechaInicial' => '13/11/2018', 'fechaFin' => '18/11/2030' ,'psicologo' => 'Maria Luna Lunera', 'candidato' => 'Daniel Prieto', 'observaciones' => ''],
 ['id' => '47','descripcion' => 'Tecnico de Farmacia', 'contacto' =>'Enrique Velardo', 'telefono' =>'959235685',  'email' => 'kikeV@gmail.com', 'direccion' =>'c/Mal Augurio 28' ,'poblacion' =>' La Puebla de Guzman', 'cp' => '21004', 'id_provincia' => '21', 'provincia' => 'Huelva', 'estado' =>' P', 'fechaInicial' => '13/11/2018', 'fechaFin' => '18/11/2030' ,'psicologo' => 'Maria Luna Lunera', 'candidato' => 'Daniel Prieto', 'observaciones' => ''],
 ['id' => '48 ','descripcion' => 'Tecnico de Farmacia', 'contacto' =>'Enrique Velardo', 'telefono' =>'959235685',  'email' => 'kikeV@gmail.com', 'direccion' =>'c/Mal Augurio 28' ,'poblacion' =>' La Puebla de Guzman', 'cp' => '21004', 'id_provincia' => '21', 'provincia' => 'Huelva', 'estado' =>' P', 'fechaInicial' => '13/11/2018', 'fechaFin' => '18/11/2030' ,'psicologo' => 'Maria Luna Lunera', 'candidato' => 'Daniel Prieto', 'observaciones' => ''],
 ['id' => '49','descripcion' => 'Tecnico de Farmacia', 'contacto' =>'Enrique Velardo', 'telefono' =>'959235685',  'email' => 'kikeV@gmail.com', 'direccion' =>'c/Mal Augurio 28' ,'poblacion' =>' La Puebla de Guzman', 'cp' => '21004', 'id_provincia' => '21', 'provincia' => 'Huelva', 'estado' =>' P', 'fechaInicial' => '13/11/2018', 'fechaFin' => '18/11/2030' ,'psicologo' => 'Maria Luna Lunera', 'candidato' => 'Daniel Prieto', 'observaciones' => ''],
 ['id' => '50','descripcion' => 'Tecnico de Farmacia', 'contacto' =>'Enrique Velardo', 'telefono' =>'959235685',  'email' => 'kikeV@gmail.com', 'direccion' =>'c/Mal Augurio 28' ,'poblacion' =>' La Puebla de Guzman', 'cp' => '21004', 'id_provincia' => '21', 'provincia' => 'Huelva', 'estado' =>' P', 'fechaInicial' => '13/11/2018', 'fechaFin' => '18/11/2030' ,'psicologo' => 'Maria Luna Lunera', 'candidato' => 'Daniel Prieto', 'observaciones' => ''],
 ['id' => '51','descripcion' => 'Tecnico de Farmacia', 'contacto' =>'Enrique Velardo', 'telefono' =>'959235685',  'email' => 'kikeV@gmail.com', 'direccion' =>'c/Mal Augurio 28' ,'poblacion' =>' La Puebla de Guzman', 'cp' => '21004', 'id_provincia' => '21', 'provincia' => 'Huelva', 'estado' =>' P', 'fechaInicial' => '13/11/2018', 'fechaFin' => '18/11/2030' ,'psicologo' => 'Maria Luna Lunera', 'candidato' => 'Daniel Prieto', 'observaciones' => ''],
 ['id' => '52','descripcion' => 'Tecnico de Farmacia', 'contacto' =>'Enrique Velardo', 'telefono' =>'959235685',  'email' => 'kikeV@gmail.com', 'direccion' =>'c/Mal Augurio 28' ,'poblacion' =>' La Puebla de Guzman', 'cp' => '21004', 'id_provincia' => '21', 'provincia' => 'Huelva', 'estado' =>' P', 'fechaInicial' => '13/11/2018', 'fechaFin' => '18/11/2030' ,'psicologo' => 'Maria Luna Lunera', 'candidato' => 'Daniel Prieto', 'observaciones' => '']];

